# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAutoSync < Formula
  desc ""
  homepage "https://github.com/GitJournal/git-auto-sync"
  version "1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.4/git-auto-sync_1.4_Darwin_x86_64.tar.gz"
      sha256 "7bd3552f7aa7fa174289b05c4da9aaa9048e6268c0f11d818c0592babbf7dcfd"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.4/git-auto-sync_1.4_Darwin_arm64.tar.gz"
      sha256 "4452d4341279211593a47070dd20ff65e31b2c7dd8fa045fd338af9e29672f9d"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.4/git-auto-sync_1.4_Linux_arm64.tar.gz"
      sha256 "b19b20fcb658332cf63299d9b1cfeaffba522b3401a19266c42995f0ce29bbee"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.4/git-auto-sync_1.4_Linux_x86_64.tar.gz"
      sha256 "53273c30afc4c39e8916310e01fc3d822dac26fb8f5b206e7f032f132210ed0d"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.4/git-auto-sync_1.4_Linux_armv6.tar.gz"
      sha256 "908193afed243ab800d08f4649bfcc92fa60f47e594930829bd239802f527888"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
  end
end
