# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAutoSync < Formula
  desc ""
  homepage "https://github.com/GitJournal/git-auto-sync"
  version "1.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.5/git-auto-sync_1.5_Darwin_arm64.tar.gz"
      sha256 "02423943245a22d25d24d8fa8825fa5cc5768cd476ef25f99215dd57e650574c"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.5/git-auto-sync_1.5_Darwin_x86_64.tar.gz"
      sha256 "b11a4652b1a8a0e4ff86d186021926a8e27cf9f19377af5bcbd40089be33460f"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.5/git-auto-sync_1.5_Linux_arm64.tar.gz"
      sha256 "b1833a340c179b76e427b01e7db22452d65fb761ef0ed6fa0dbae1e0e839cb0b"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.5/git-auto-sync_1.5_Linux_x86_64.tar.gz"
      sha256 "da271166b637b584d002c7a75a39010f49bbb8ab491b73ccf34d12475b0f2dd0"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.5/git-auto-sync_1.5_Linux_armv6.tar.gz"
      sha256 "465af574237b1775f9e10f0376cd28fadc0f543dc6b9ac1e108abebc7666700b"

      def install
        bin.install "git-auto-sync"
        bin.install "git-auto-sync-daemon"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
  end
end
