# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAutoSync < Formula
  desc ""
  homepage "https://github.com/GitJournal/homebrew-tap"
  version "1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.0/git-auto-sync_1.0_Darwin_arm64.tar.gz"
      sha256 "f6b974327a5d0d6db782fd061818fa9800598c15904c9f01e2cf10e2d5ca9811"

      def install
        bin.install "git-auto-sync"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.0/git-auto-sync_1.0_Darwin_x86_64.tar.gz"
      sha256 "e991ee5db0b00778ae194e62f1f1457417c4d06f0c8c321d0c52eed6758912e5"

      def install
        bin.install "git-auto-sync"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.0/git-auto-sync_1.0_Linux_armv6.tar.gz"
      sha256 "3abe3b72c0964da0b4bda6b689434132c046dbea7d16095e833db5034f51cb32"

      def install
        bin.install "git-auto-sync"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.0/git-auto-sync_1.0_Linux_x86_64.tar.gz"
      sha256 "d863e0659ad2b69af9f14f38d61499c652dbb7e0ade55dc78c3c677d5acb0ba2"

      def install
        bin.install "git-auto-sync"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GitJournal/git-auto-sync/releases/download/v1.0/git-auto-sync_1.0_Linux_arm64.tar.gz"
      sha256 "40ccf3da46b030e1b028206bc558767d2306074c834c19c804bece158360cd5e"

      def install
        bin.install "git-auto-sync"
        bash_completion.install "completions/bash_autocomplete"
        zsh_completion.install "completions/zsh_autocomplete"
      end
    end
  end
end
